<?php
/**
 * Ofertasmall Lojas - Import Background Process
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  Pablo S G Pacheco
 */

namespace TxToIT\OML;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'TxToIT\OML\Import_Background_Process' ) ) {
	class Import_Background_Process extends \WP_Background_Process {
		/**
		 * @var string
		 */
		protected $action = '_oml_store_import_process';
		public static $current_parent_id = '';

		protected function task( $item ) {
			$stores = get_option( '_oml_stores_from_api' );
			$store  = wp_list_filter( $stores, array(
				'id' => $item
			) );

			//error_log( '-----bkg-process-----' );
			//error_log( print_r( $item, true ) );
			//error_log( print_r( $store, true ) );

			if ( ! empty( $store ) ) {
				$import = new Import( array(
					'stores_post_type' => Store_CPT::$post_type,
					'stores_tax'       => Store_Tax::$taxonomy
				) );
				reset( $store );
				$first_key = key( $store );
				$import->import_store( $store[ $first_key ] );

				$count = get_option( '_oml_import_count', 0 );
				$count ++;
				update_option( '_oml_import_count', $count, false );

				return false;
			}
		}

		protected function complete() {
			parent::complete(); // TODO: Change the autogenerated stub
			//update_option( '_oml_import_count', 0, false );
			//delete_option( '_oml_stores_from_api' );
		}
	}
}